apiVersion: apps/v1
kind: Deployment
metadata:
  name: wbapp
  namespace: default
  labels:
    app: #pyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wbapp
  template:
    metadata:
      labels:
        app: #pyapp
    spec:
      containers:
      - name: pyapp
        image: #spkosana/fastapi:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: #python-service
  namespace: #fastapi
spec:
  selector:
    app: #pyapp
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer